feat: replace 3rd party tools to pure shell script
also add "make copy" as a helper cmd to update hooks in existed local projects

BREAKING CHANGE: No tools but pure script

diff --git a/hooks/commit-msg b/hooks/commit-msg
--- a/hooks/commit-msg
+++ b/hooks/commit-msg
@@ -1,44 +1,31 @@
-#!/usr/local/opt/pre-commit/libexec/bin/python3
-# File generated by pre-commit: https://pre-commit.com
-# ID: 138fd403232d2ddd5efb44317e38bf03
-import os
-import sys
 
-# we try our best, but the shebang of this script is difficult to determine:
-# - macos doesn't ship with python3
-# - windows executables are almost always `python.exe`
-# therefore we continue to support python2 for this small script
-if sys.version_info < (3, 3):
-    from distutils.spawn import find_executable as which
-else:
-    from shutil import which
+#!/bin/bash
 
-# work around https://github.com/Homebrew/homebrew-core/issues/30445
-os.environ.pop('__PYVENV_LAUNCHER__', None)
+# Git COMMIT-MSG hook for validating commit message
+#See https://docs.google.com/document/d/1rk04jEuGfk9kYzfqCuOlPTSJw3hEDZJTBN5E5f1SALo/edit
 
-# start templated
-INSTALL_PYTHON = '/usr/local/opt/pre-commit/libexec/bin/python3'
-ARGS = ['hook-impl', '--config=.pre-commit-config.yaml', '--hook-type=commit-msg', '--skip-on-missing-config']
-# end templated
-ARGS.extend(('--hook-dir', os.path.realpath(os.path.dirname(__file__))))
-ARGS.append('--')
-ARGS.extend(sys.argv[1:])
+MESSAGE=`head -n 1 "$1"`
 
-DNE = '`pre-commit` not found.  Did you forget to activate your virtualenv?'
-if os.access(INSTALL_PYTHON, os.X_OK):
-    CMD = [INSTALL_PYTHON, '-mpre_commit']
-elif which('pre-commit'):
-    CMD = ['pre-commit']
-else:
-    raise SystemExit(DNE)
+# MAX_LENGTH=70
+TYPES="feat fix docs style refactor perf test build ci chore revert"
+PATTERN="^([a-z]+)(\([a-z\-\*]+\)){0,1}\:\ (.*)$"
 
-CMD.extend(ARGS)
-if sys.platform == 'win32':  # https://bugs.python.org/issue19124
-    import subprocess
+# if [[ ${MESSAGE} > $MAX_LENGTH ]]; then
+#      echo "ERROR: Commit message was ${#MESSAGE} characters long, but should be at most $MAX_LENGTH characters"
+#      exit 1
+# fi
 
-    if sys.version_info < (3, 7):  # https://bugs.python.org/issue25942
-        raise SystemExit(subprocess.Popen(CMD).wait())
-    else:
-        raise SystemExit(subprocess.call(CMD))
-else:
-    os.execvp(CMD[0], CMD)
+if [[ "$MESSAGE" =~ ^WIP ]]; then
+    exit 0
+fi
+
+if ! [[ "$MESSAGE" =~ $PATTERN ]]; then
+    echo "ERROR: Commit message did not match format 'type(scope): subject'"
+    exit 1
+fi
+TYPE=${BASH_REMATCH[1]}
+
+if ! [[ $TYPES =~ (^| )$TYPE($| ) ]]; then
+    echo "ERROR: Commit message's type '$TYPE' must be one of '$TYPES'"
+    exit 1
+fi
